# syntax=docker/dockerfile:1

#############################################
# Base image — Node.js LTS (20.x) on Debian
# slim. Debian (not Alpine) is used because
# Prisma's query engine needs glibc, which
# avoids extra binary-target configuration.
#############################################
FROM node:20-bookworm-slim AS base
WORKDIR /app
# OpenSSL is required by the Prisma engines at runtime/build time.
RUN apt-get update -y && apt-get install -y openssl ca-certificates && rm -rf /var/lib/apt/lists/*

#############################################
# Stage 1: deps — install npm dependencies
#############################################
FROM base AS deps
COPY package.json package-lock.json ./
RUN npm ci

#############################################
# Stage 2: builder — generate Prisma client
# and build the Next.js application
#############################################
FROM base AS builder
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Generate the Prisma client. This only reads prisma/schema.prisma to
# generate TypeScript/JS client code — it does NOT connect to a database
# and does NOT run any migrations.
RUN npx prisma generate

# Build-time placeholder so `next build` (which loads next.config.ts /
# validates env at build time) doesn't fail when DATABASE_URL isn't
# provided as a build secret. The real value is injected at container
# runtime via Kubernetes Secrets / docker-compose env vars — this value
# is never used to actually connect to a database during build.
ENV DATABASE_URL="postgresql://placeholder:placeholder@placeholder:5432/placeholder"
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

#############################################
# Stage 3: runner — minimal production image
#############################################
FROM base AS runner
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Run as a non-root user for better container security.
RUN addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

# Next.js standalone output: a minimal server.js plus only the
# node_modules actually needed at runtime.
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

# Prisma CLI + schema are kept in the final image so that
# `npx prisma migrate deploy` can be run from inside the running
# container/pod after deployment (migrations are intentionally NOT run
# during the image build).
COPY --from=builder --chown=nextjs:nodejs /app/node_modules ./node_modules
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma
COPY --from=builder --chown=nextjs:nodejs /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder --chown=nextjs:nodejs /app/package.json ./package.json

# Ensure the uploads directory used by app/api/upload exists and is
# writable by the non-root user. NOTE: this is local container disk —
# see README for persistence considerations under Kubernetes.
RUN mkdir -p ./public/uploads && chown -R nextjs:nodejs ./public/uploads

USER nextjs

EXPOSE 3000

# server.js is generated by the Next.js standalone build output.
CMD ["node", "server.js"]
