apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: kpk-citizen-portal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: standard   # Uncomment and set to match your cluster's
  #                               # available StorageClass if the default
  #                               # StorageClass isn't suitable.
