apiVersion: v1
kind: Service
metadata:
  name: kpk-citizen-portal-service
  namespace: kpk-citizen-portal
  labels:
    app: kpk-citizen-portal
spec:
  type: LoadBalancer
  selector:
    app: kpk-citizen-portal
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
